# Generated by Django 5.2.12 on 2026-03-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('movie_id', models.IntegerField()),
                ('movie_title', models.CharField(max_length=300)),
                ('showtime', models.CharField(max_length=300)),
                ('seats', models.JSONField(default=list)),
                ('total_price', models.FloatField()),
                ('status', models.CharField(default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(db_index=True)),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('author', models.CharField(default='Ghost Viewer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
